### ISSUE TITLE
Logo component

### ISSUE THREAD

**Issue by rrudol** [SeniorNinjaRockstars/interviews#12]
- [ ] Prepare SVG
- [ ] Create component
- [ ] Cusomizable `fill` property

**Comment by tomaszgil** [comment]
![Logo presentation](https://user-images.githubusercontent.com/17861616/55276508-8813af00-52f4-11e9-8340-600268654ab5.png)
![Logo presentation (white)](https://user-images.githubusercontent.com/17861616/55276520-be512e80-52f4-11e9-9d03-8120a77f8af0.png)
