### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by rrudol** [SeniorNinjaRockstars/interviews#19]
- [x] Create component
- [x] Filled with color on hover
- [ ] Color depending on props
- [ ] It should be `<a>` no `<button>`
- [ ] Should wrap Gatsby Link component

**Comment by tomaszgil** [comment]
For now we don't have additional colors for buttons and when you want to use a component as a Gatsby Link you simply pass `as={Link}` prop to the `Button` component, so there's no need to have a separate wrapper for that. All other criteria are matched, so after merging #27 I suggest closing this task.
