### ISSUE TITLE
Landing page - design

### ISSUE THREAD

**Issue by tomaszgil** [SeniorNinjaRockstars/interviews#7]
![homepage python](https://user-images.githubusercontent.com/17861616/53922036-12a91b80-4073-11e9-98d3-c2b2b909188e.png)
![homepage c](https://user-images.githubusercontent.com/17861616/53922037-12a91b80-4073-11e9-8fc9-3d25cf9fa663.png)
![homepage js](https://user-images.githubusercontent.com/17861616/53922038-1341b200-4073-11e9-8a4f-f04b1696e21a.png)

**Comment by tomaszgil** [comment]
![homepage python](https://user-images.githubusercontent.com/17861616/53922036-12a91b80-4073-11e9-98d3-c2b2b909188e.png)
![homepage c](https://user-images.githubusercontent.com/17861616/53922037-12a91b80-4073-11e9-8fc9-3d25cf9fa663.png)
![homepage js](https://user-images.githubusercontent.com/17861616/53922038-1341b200-4073-11e9-8a4f-f04b1696e21a.png)

**Comment by rrudol** [comment]
@tomaszgil  I have a few questions

Does the button has an active state?

How do we decide which technology show on the landing page?

**Comment by tomaszgil** [comment]
1. I suppose filled with color on hover (if that's what you mean by _active_).
2. I have an idea of combining a sort of a carousel  (with either those two lines of text comming up or just typing effect for the last word) with a drawing effect on the svg to the right. So I guess it doesn't really matter?

**Comment by rrudol** [comment]
I ❤️ idea of SVG drawing effect

**Comment by tomaszgil** [comment]
This page has been designed and implemented.
